---
version: '3'
services:
  s3-uploader:
    build: .
    image: ghcr.io/torresmvl/s3-uploader:latest
    command: pm2 start src/app.js -i max --watch --no-daemon
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      S3_ENDPOINT: http://minio:9000
      S3_PORT: 9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 3000:3000
    volumes:
      - ./src:/api/src
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/status']
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - 9000:9000
    volumes:
      - data:/data
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data: {}
